version: '3.7'
services:
  redisgraph:
    image: rolandinsh/redisgraph
    container_name: redisg
#    network_mode: bridge
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - redisgn
networks:
  redisgn:
#volumes:
#    mdb8: {}
